# Generated by Django 5.2 on 2025-04-11 11:59

import django.db.models.deletion
import ebooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='default.png', upload_to='ebook_pics')),
                ('url', models.URLField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='ebook_audio/', validators=[ebooks.models.validate_audio_file])),
                ('duration', models.DurationField(blank=True, help_text='Duration of the audio in HH:MM:SS', null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ebooks.type')),
            ],
        ),
    ]
